# Database connection properties
 spring:
 datasource:
 url: jdbc:postgresql://localhost:5433/WrestlingTestDB
 username: postgres
 password: adminPassword123

 # Hibernate properties
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate.format_sql: true

